version: '3.3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: vnb2024
      MYSQL_ROOT_PASSWORD: vnb2024
    ports:
      - 3309:3306
    volumes:
      - datadb:/var/lib/mysql
      - ./db:/db

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: vnb2024 
  nginx:
    build: ./docker/nginx
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8090:80
  php:
    build: ./docker/php
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
volumes: 
    datadb:

